version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"  # Maps host port 3000 to container port 80
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"  # Maps host port 5000 to container port 5000
    networks:
      - app-network
    environment:
      - MONGO_URI=<MONGO_URI=mongodb+srv://myUser:myPassword@cluster0.mongodb.net/myDatabase?retryWrites=true&w=majority>  # Replace with your MongoDB connection string

networks:
  app-network:
    driver: bridge
